spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/security
    username: sa
    password:

  security:
    user:
      name: admin
      password: root

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug