spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/security
    username: sa
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug